---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafkabanasucre
  namespace: cabanasucre
spec:
  kafka:
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: '3.2'
      inter.broker.protocol.version: '3.2'
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: true
      class: openebs-lvm-localpv-slow
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 19092
        type: nodeport
        tls: false
        configuration:
          brokers:
          - broker: 0
            nodePort: 31092
          - broker: 1
            nodePort: 31093
          - broker: 2
            nodePort: 31094
    template:
      pod:
        securityContext:
          runAsUser: 0
          fsGroup: 0
    version: 3.2.0
    replicas: 3
    rack:
      topologyKey: kubernetes.io/hostname
  entityOperator:
    topicOperator: {}
    userOperator: {}
  zookeeper:
    storage:
      type: persistent-claim
      size: 1Gi
      class: openebs-lvm-localpv-slow
      deleteClaim: true
    template:
      pod:
        securityContext:
          runAsUser: 0
          fsGroup: 0
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: strimzi.io/name
                      operator: In
                      values:
                        - kafkabanasucre-zookeeper
                topologyKey: kubernetes.io/hostname
    replicas: 3
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: bouillage.temperature
  labels:
    strimzi.io/cluster: kafkabanasucre
  namespace: cabanasucre 
spec: 
  partitions: 1
  replicas: 3
  config:
    cleanup.policy: delete
    retention.ms: -1
    retention.bytes: 2147483648 # 2Gi
    segment.bytes: 536870912 # 512Mi
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: bouillage.niveau
  labels:
    strimzi.io/cluster: kafkabanasucres
  namespace: cabanasucre 
spec: 
  partitions: 1
  replicas: 3
  config:
    cleanup.policy: delete
    retention.ms: -1
    retention.bytes: 2147483648 # 2Gi
    segment.bytes: 536870912 # 512Mi
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: bouillage.alertes
  labels:
    strimzi.io/cluster: kafkabanasucre
  namespace: cabanasucre 
spec: 
  partitions: 1
  replicas: 3
  config:
    cleanup.policy: delete
    retention.ms: -1
    retention.bytes: 2147483648 # 2Gi
    segment.bytes: 536870912 # 512Mi
